Repository Real-Dev-Squad/website-backend, pull requests merged in 2020-12, with the labels that each got.

#90 Added pullrequests/:id API route
  config/custom-environment-variables.js
  config/default.js
  controllers/pullRequestsController.js
  routes/index.js
  routes/pullrequests.js
  services/githubService.js
  utils/fetch.js
  utils/swaggerDefinition.js
Labels: enhancement, feature-task

#95 Changed API routes and functions to take `username` of user along with `id`
  controllers/pullRequestsController.js
  controllers/usersController.js
  middlewares/authenticate.js
  models/users.js
  routes/pullrequests.js
  routes/users.js
  services/githubService.js
Labels: bug

#97 Fetch oldest Open PRs
  controllers/pullRequestsController.js
  routes/pullrequests.js
  services/githubService.js
Labels: feature-task

#104 Updating API endpoint for fetching pullrequests
  routes/pullrequests.js
Labels: feature-task

#87 get challenge api
  config/development.js
  controllers/roadmap-site/challengeController.js
  models/roadmap-site/challenges.js
  models/roadmap-site/subscribe-challenge.js
  public/apiSchema.json
  routes/index.js
  routes/roadmap-site/challenges.js
  routes/roadmap-site/index.js
Labels: feature-task
