Repository Real-Dev-Squad/website-backend, pull requests merged in 2020-11, with the labels that each got.

#74 Fix content-type check after CORS setup
  middlewares/index.js
Labels: bug

#85 added library function for network call
  lib/fetch.js
  package-lock.json
  package.json
Labels: feature-task

#91 Add response headers in API
  app.js
  middlewares/responseHeaders.js
Labels: enhancement
