Repository Real-Dev-Squad/website-backend, pull requests merged in 2021-03, with the labels that each got.

#223 Create function for Mapping username-userId
  utils/users.js
Labels: feature-task

#232 Added logs for processes being executed
  scripts/local-test.js
Labels: enhancement

#225 `/auctions` APIs for crypto
  controllers/auctionController.js
  docs/swaggerDefinition.js
  middlewares/validators/auctions.js
  models/auctions.js
  public/apiSchema.json
  routes/auctions.js
  routes/index.js
Labels: feature-task

#242 Saves bid and quantity as integer in db in `/auctions` routes
  models/auctions.js
Labels: bug-fix

#252 Integrates wallet into auctions
  controllers/auctionController.js
  models/auctions.js
Labels: enhancement

#222 Endpoints for Creating stocks and trading
  controllers/stocksController.js
  controllers/tradingController.js
  docs/swaggerDefinition.js
  middlewares/authorization.js
  middlewares/validators/stocks.js
  middlewares/validators/trading.js
  models/members.js
  models/stocks.js
  models/trading.js
  public/apiSchema.json
  routes/index.js
  routes/stocks.js
  routes/trading.js
Labels: WIP, feature-task

#268 Checks if OAuth credentials are set up or not
  scripts/local-test.js
Labels: bug-fix

#285 Create and initialize wallet if not found for user
  constants/wallets.js
  controllers/usersController.js
  controllers/walletsController.js
  models/users.js
  models/wallets.js
Labels: enhancement, feature task

#282 Added get wallet by username API
  controllers/walletsController.js
  middlewares/authorization.js
  models/members.js
  public/apiSchema.json
  routes/wallets.js
Labels: feature task
