Repository Real-Dev-Squad/website-backend, pull requests merged in 2021-05, with the labels that each got.

#265 Track the stocks purchased by users
  controllers/stocks.js
  controllers/trading.js
  docs/swaggerDefinition.js
  models/stocks.js
  public/apiSchema.json
  routes/stocks.js
  services/tradingService.js
Labels: feature task

#365 Created Backend Flow doc of website-backend
  docs/backendFlow.md
  package-lock.json
  package.json
Labels: documentation

#359 Using firebase tools from local node_modules
  .github/workflows/test.yml
  CONTRIBUTING.md
  package-lock.json
  package.json
Labels: enhancement
