Repository Real-Dev-Squad/website-backend, pull requests merged in 2021-06, with the labels that each got.

#296 New members API for members page
  models/members.js
  test/fixtures/user/user.js
  test/integration/members.test.js
Labels: feature task, tests

#372 Issue#283 wallet tests
  test/fixtures/wallet/wallet.js
  test/integration/wallet.test.js
Labels: tests

#404 added .js extensions
  routes/index.js
Labels: beginner friendly
