Repository Real-Dev-Squad/website-backend, pull requests merged in 2021-04, with the labels that each got.

#287 Removed `Controller` from filename under folder `controller` and updated references to the files
  CONTRIBUTING.md
  controllers/auction.js
  controllers/auth.js
  controllers/badge.js
  controllers/challenge.js
  controllers/contributions.js
  controllers/health.js
  controllers/members.js
  controllers/pullRequests.js
  controllers/stocks.js
  controllers/tasks.js
  controllers/trading.js
  controllers/users.js
  controllers/wallets.js
  middlewares/authorizeOwner.js
  routes/auctions.js
  routes/auth.js
  routes/badges.js
  routes/challenges.js
  routes/contributions.js
  routes/healthCheck.js
  routes/members.js
  routes/pullrequests.js
  routes/stocks.js
  routes/tasks.js
  routes/trading.js
  routes/users.js
  routes/wallets.js
  test/integration/auth.test.js
  test/integration/badge.test.js
  test/integration/contributions.test.js
  test/integration/health.test.js
  test/integration/members.test.js
  test/integration/tasks.test.js
  test/integration/users.test.js
Labels: beginner friendly, feature task, good first issue

#295 Checks if user has sufficient items to auction
  controllers/auction.js
Labels: enhancement

#227 Recruiter Form Feature
  controllers/recruiters.js
  docs/swaggerDefinition.js
  middlewares/validators/recruiter.js
  models/members.js
  models/recruiters.js
  public/apiSchema.json
  routes/members.js
  test/fixtures/recruiter/recruiter.js
  test/integration/recruiters.test.js
  test/unit/models/recruiters.test.js
Labels: feature task

#312 Remove firestore-private-key.json usage
  .gitignore
  CONTRIBUTING.md
  README.md
  config/custom-environment-variables.js
  config/default.js
  config/test.js
  package-lock.json
  package.json
  scripts/local-test.js
  test/utils/cleanDb.js
  utils/firestore.js
Labels: enhancement

#259 Removed extra validation fields from user validator
  middlewares/validators/user.js
Labels: enhancement

#330 Added emojis in validate-config messages
  scripts/validateSetup.js
Labels: enhancement

#332 Fixed epoch datatype in tasks and tests #331
  constants/tasks.js
  middlewares/validators/tasks.js
  test/integration/tasks.test.js
  test/unit/utils/users.test.js
Labels: bug, tests

#328 Adds pagination to `pullrequests` routes: `/stale` and `/open`
  controllers/pullRequests.js
  routes/pullrequests.js
  services/githubService.js
Labels: enhancement

#310 adds GET `/auctions` integration tests
  routes/auctions.js
  test/fixtures/auctions/auctions.js
  test/fixtures/currencies/currencies.js
  test/integration/auction.test.js
Labels: tests
