Repository Real-Dev-Squad/website-backend, pull requests merged in 2021-02, with the labels that each got.

#156 returning `phone` and `email` only for users/self route when query `private` is true
  controllers/usersController.js
  models/users.js
  test/integration/usersController.test.js
  test/utils/addUser.js
Labels: enhancement

#176 adds fetchUserTasks model function back to fix broken contributions API
  models/tasks.js
Labels: bug-fix

#177 Scripts updated to run tests on windows
  CONTRIBUTING.md
  package.json
Labels: bug-fix

#167 added response in case of no member found
  controllers/membersController.js
Labels: refactor

#189 Changing compound query for `/tasks/self` so that manual indexing is not required
  models/tasks.js
Labels: bug-fix

#165 Adds tests for GET /members API
  test/fixtures/user/user.js
  test/integration/membersController.test.js
  test/integration/tasksController.test.js
  test/integration/usersController.test.js
Labels: enhancement

#197 Updates packages
  package-lock.json
  package.json
  scripts/local-test.js
Labels: dependencies
