Repository Real-Dev-Squad/website-backend, pull requests merged in 2022-04, with the labels that each got.

#526 add PATCH /users/:userId endpoint and logging endpoint
  constants/logs.js
  constants/profileDiff.js
  constants/users.js
  controllers/logs.js
  controllers/users.js
  models/logs.js
  models/profileDiffs.js
  routes/index.js
  routes/logs.js
  routes/users.js
  test/fixtures/profileDiffs/profileDiffs.js
  test/integration/users.test.js
Labels: backend

#525 Added /profileDiffs
  constants/users.js
  controllers/profileDiffs.js
  models/profileDiffs.js
  routes/index.js
  routes/profileDiffs.js
  test/integration/profileDiffs.test.js
Labels: backend

#569 Feature flag/add tests validator
  middlewares/validators/flag.js
  routes/flag.js
  test/fixtures/flag/flag.js
  test/integration/flag.test.js
  test/unit/models/flag.test.js
Labels: feature task

#544 add art endpoints
  controllers/arts.js
  middlewares/validators/arts.js
  models/arts.js
  routes/arts.js
  routes/index.js
  test/fixtures/arts/arts.js
  test/integration/arts.test.js
Labels: feature task

#543 add unit tests for models/auction.js
  models/auctions.js
  nyc.config.js
  scripts/tests/testUnit.sh
  test/fixtures/currencies/currencies.js
  test/integration/auction.test.js
  test/unit/models/auctions.test.js
Labels: unit test

#551 add unit tests for models/challenges and add time utils
  test/fixtures/challenges/challenges.js
  test/fixtures/time/time.js
  test/unit/models/challenges.test.js
  test/unit/utils/time.test.js
  utils/time.js
Labels: unit test
