Repository Real-Dev-Squad/website-backend, pull requests merged in 2022-08, with the labels that each got.

#679 API Sign Out Feature
  controllers/auth.js
  routes/auth.js
  test/integration/auth.test.js
Labels: feature task, backend

#693 Modified test.yml to remove test workflow on Push
  .github/workflows/test.yml
Labels: enhancement, bug-fix, tests, beginner friendly

#687 Removes temporary/one-time-use migration endpoints
  controllers/members.js
  controllers/users.js
  models/members.js
  models/users.js
  routes/members.js
  routes/users.js
  test/integration/users.test.js
  test/utils/deleteRoles.js
  test/utils/deleteRolesObject.js
Labels: refactor

#622 Feature/update authorize role
  constants/roles.js
  controllers/members.js
  middlewares/authorizeRoles.js
  models/members.js
  routes/logs.js
  routes/members.js
  routes/profileDiffs.js
  routes/stocks.js
  routes/tasks.js
  routes/users.js
  routes/wallets.js
  test/integration/authorizeRoles.test.js
Labels: enhancement
