Repository Real-Dev-Squad/website-backend, pull requests merged in 2023-02, with the labels that each got.

#832 show-achievements-badges-on-members-site
  constants/badges.js
  constants/cloudinary.js
  controllers/badge.js
  controllers/badges.js
  middlewares/validators/badges.js
  models/badges.js
  routes/badges.js
  routes/users.js
  services/imageService.js
  test/fixtures/badges/badges.js
  test/integration/badge.test.js
  test/integration/badges.test.js
  test/integration/userBadges.test.js
  utils/array.js
  utils/badges.js
Labels: feature task, draft

#911 Discord Bot API
  config/custom-environment-variables.js
  config/default.js
  config/development.js
  config/test.js
  constants/bot.js
  controllers/discord.js
  middlewares/authorizeBot.js
  middlewares/validators/discord.js
  middlewares/validators/user.js
  models/discord.js
  routes/discord.js
  routes/index.js
  services/botVerificationService.js
  test/fixtures/discord/discord.js
  test/integration/discord.test.js
  test/unit/middlewares/authorizeBot.test.js
  test/unit/models/discord.test.js
  test/utils/generateBotToken.js
Labels: feature task, tests

#920 Fixed request body of discord bot API
  middlewares/validators/discord.js
  test/fixtures/discord/discord.js
Labels: backend

#926 Created GET API for External Accounts
  controllers/external-accounts.js
  models/external-accounts.js
  routes/external-accounts.js
  test/fixtures/external-accounts/external-accounts.js
  test/integration/external-accounts.test.js
  test/unit/models/external-accounts.test.js
Labels: tests, backend
