Repository Real-Dev-Squad/website-backend, pull requests merged in 2023-07, with the labels that each got.

#1190 Patch call for updating authorization status of user on mobile app
  controllers/qrCodeAuth.js
  middlewares/validators/qrCodeAuth.js
  models/qrCodeAuth.js
  routes/auth.js
  test/fixtures/userDeviceInfo/userDeviceInfo.js
  test/integration/qrCodeAuth.test.js
  test/unit/middlewares/qrCodeAuthValidator.test.js
  test/unit/models/qrCodeAuth.test.js
Labels: feature task, tests, beginner friendly, backend

#1223 feat: return archived users if asked for using user/search endpoint
  middlewares/validators/user.js
  models/users.js
  test/integration/usersFilter.test.js
Labels: enhancement, feature task, backend

#1147 Route for adding and removing roles from a user
  controllers/users.js
  middlewares/validators/user.js
  routes/users.js
  test/fixtures/user/user.js
  test/integration/users.test.js
  test/unit/middlewares/users-validator.test.js
  test/unit/utils/users.test.js
  utils/users.js
Labels: backend

#1269 feat: validate percentComplete value to be from 0 to 100
  middlewares/validators/tasks.js
  test/integration/tasks.test.js
Labels: backend
