Repository Real-Dev-Squad/website-backend, pull requests merged in 2023-08, with the labels that each got.

#1375 [Live-Site] feat: added api to kickout peer
  controllers/events.js
  middlewares/validators/events.js
  models/events.js
  routes/events.js
Labels: live-site

#1165 [Live-Site] Feat/event join peer api
  controllers/events.js
  middlewares/validators/events.js
  models/events.js
  routes/events.js
  test/unit/models/events.test.js
Labels: live-site

#1392 FEATURE: Filter task based assignee and task title
  controllers/tasks.js
  middlewares/validators/tasks.js
  models/tasks.js
  test/integration/tasks.test.js
  test/unit/middlewares/tasks-validator.test.js
  test/unit/models/tasks.test.js
  test/unit/utils/transformQuery.test.js
  utils/tasks.js
Labels: feature task, backend

#1380 Add new route for Unique Username Generation
  controllers/users.js
  middlewares/validators/user.js
  models/users.js
  routes/users.js
  test/fixtures/user/user.js
  test/integration/users.test.js
  test/unit/models/users.test.js
Labels: feature task, tests, backend

#1425 [Live-Site] feat: create generate event code API
  constants/events.js
  controllers/events.js
  middlewares/validators/events.js
  models/events.js
  routes/events.js
  test/fixtures/events/event-codes.js
  test/integration/events.test.js
  test/unit/models/events.test.js
Labels: live-site

#1434 [Live-Site] feat: create get event codes API
  controllers/events.js
  middlewares/validators/events.js
  models/events.js
  routes/events.js
  test/fixtures/events/event-codes.js
  test/fixtures/events/events.js
  test/integration/events.test.js
  test/unit/models/events.test.js
Labels: live-site
