Repository Real-Dev-Squad/website-backend, pull requests merged in 2023-06, with the labels that each got.

#1123 test: unit test for user util - getUsernamesFromPRs
  test/fixtures/pullrequests/pullrequests.js
  test/unit/utils/users.test.js
  utils/users.js
Labels: unit test, backend

#1124 add tests for blocking archived users from discord actions
  test/fixtures/discordactions/discordactions.js
  test/integration/discord.test.js
Labels: tests

#994 [Live-Site] Feat/event room apis
  constants/events.js
  controllers/events.js
  middlewares/validators/events.js
  models/events.js
  routes/events.js
  routes/index.js
  services/index.js
  test/fixtures/events/events.js
  test/integration/events.test.js
  test/unit/models/events.test.js
  test/unit/utils/events.test.js
  utils/events.js
Labels: live-site

#1174 [Live-Site] Add correct roomId and userId in authToken
  controllers/events.js
Labels: live-site

#1182 Adding Tests for Arts Validator Middleware
  test/unit/middlewares/arts-validator.test.js
Labels: tests

#1191 Remove user personal details filters data
  controllers/users.js
  test/integration/usersFilter.test.js
Labels: backend
